name: Sync to GitLab

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  push-to-gitlab:
    if: github.repository == 'Bashamega/WebDevTools'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all commit history to avoid shallow clone issues

      - name: Set up Git for GitLab
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Add GitLab remote
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git remote add gitlab https://oauth2:$GITLAB_TOKEN@gitlab.com/bashaHub/web-dev-tools.git
          git fetch gitlab

      - name: Push changes to GitLab
        run: |
          git push gitlab HEAD:main --force  # Push the current branch to the main branch on GitLab
